heat_template_version: 2014-10-16
parameters:
  db_root_password:
    type: string
  db_name: 
    type: string
  db_username: 
    type: string
  db_password: 
    type: string

    
resources:
  software-init:
    type: OS::Heat::MultipartMime
    properties:
      parts:
        - config: { get_resource: DBInstall }
        - config: { get_resource: DBSetup }
      
  DBInstall:
    type: OS::Heat::CloudConfig
    properties:
      cloud_config:
        merge_how: 'dict(recurse_array,no_replace)+list(append)'
        packages:
          - mariadb-server
          
  DBSetup:
    type: OS::Heat::SoftwareConfig
    depends_on: DBInstall
    properties:
      config: 
        str_replace: 
          template: { get_file: ../scripts/dbsetup.sh }
          params:
            db_rootpassword: { get_param: db_root_password }
            db_name: { get_param: db_name }
            db_user: { get_param: db_username }
            db_password: { get_param: db_password }
outputs:
  config:
    value: { get_resource: software-init }
