heat_template_version: 2014-10-16
parameters:
  db_root_password:
    type: string
  db_name: 
    type: string
  db_username: 
    type: string
  db_password: 
    type: string

    
resources:
  software-init:
    type: OS::Heat::MultipartMime
    properties:
      parts:
        - config: { get_resource: DBSetup }
      
  DBSetup:
    type: OS::Heat::SoftwareConfig
    properties:
      config: 
        str_replace: 
          template: { get_file: ../scripts/dbsetup.sh }
          params:
            db_rootpassword: { get_param: db_root_password }
            db_name: { get_param: db_name }
            db_user: { get_param: db_username }
            db_password: { get_param: db_password }
outputs:
  config:
    value: { get_resource: software-init }
